### ISSUE TITLE
Consumption optimisation

### ISSUE THREAD

**Issue by DeGaMon** [jancelin/MultiProbeCase#2]
# Goals
Optimize satellite's electric consumption :
- [x] Implement sleeping periods.
- [ ] Put peripherals to sleep (realy).
- [ ] Use low energy communication protocol (BLE, Bluetooth SNIFF).
- [ ] Low energy SD card logging.

# Done
Satellite processes data inside ```loop()``` and goes to sleep waiting for the next measurement.

# ToDo
Put peripherals to sleep.
Implement low energy protocol.
Measure smallest measurement interval configurable.
Implement low energy logging on SD card.
